// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !plan9 && !windows && linux

// Copyright 2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Unmount a filesystem at the specified path.
//
// Synopsis:
//
//	mknod PATH TYPE [MAJOR MINOR]
//
// Description:
//
//	Creates a special file at PATH of the given TYPE. If TYPE is b, c or u,
//	the MAJOR and MINOR number must be specified. If the TYPE is p, they
//	must not be specified.
package bbmknod

import (
	"flag"
	"log"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

func registeredMain() {
	flag.Parse()
	if err := mknod(flag.Args()); err != nil {
		log.Fatalf("mknod: %v", err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("mknod", registeredInit, registeredMain)
}
