// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2014-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Print environment variables.
//
// Synopsis:
//
//	printenv
package bbprintenv

import (
	"fmt"
	"io"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

func printenv(w io.Writer, args ...string) {
	if len(args) == 0 {
		e := os.Environ()

		for _, v := range e {
			fmt.Fprintf(w, "%v\n", v)
		}
		return
	}

	for _, arg := range args {
		v, ok := os.LookupEnv(arg)
		if ok {
			fmt.Fprintln(w, v)
		}
	}
}

func registeredMain() {
	printenv(os.Stdout, os.Args[1:]...)
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("printenv", registeredInit, registeredMain)
}
