// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2012-2018 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// mv renames files and directories.
//
// Synopsis:
//
//	mv SOURCE [-u] TARGET
//	mv SOURCE... [-u] DIRECTORY
//
// Author:
//
//	Beletti (rhiguita@gmail.com)
package bbmv

import (
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/core/mv"
)

func busyboxInit1() {
	log.SetFlags(0)
}

func registeredMain() {
	cmd := mv.New()
	err := cmd.Run(os.Args[1:]...)
	if err != nil {
		log.Fatal("mv: ", err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
	busyboxInit1()
}
func init() {
	bbmain.Register("mv", registeredInit, registeredMain)
}
