// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2013-2023 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// xargs reads space, tab, newline and end-of-file delimited strings from the
// standard input and executes utility with the strings as arguments.
//
// Synopsis:
//
//	xargs [OPTIONS] [COMMAND [ARGS]...]
//
// Options:
//
//	-n: max number of arguments per command
//	-t: enable trace mode, each command is written to stderr
//	-p: the user is asked whether to execute utility at each invocation
//	-0: use a null byte as the input argument delimiter
package bbxargs

import (
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/core/xargs"
)

func busyboxInit1() {
	log.SetFlags(0)
}

func registeredMain() {
	cmd := xargs.New()
	err := cmd.Run(os.Args[1:]...)
	if err != nil {
		log.Fatal("xargs: ", err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
	busyboxInit1()
}
func init() {
	bbmain.Register("xargs", registeredInit, registeredMain)
}
