// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build (!tinygo || tinygo.enable) && linux

// Copyright 2018 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbvboot

import (
	"crypto/sha1"
	"crypto/sha256"
	"flag"
	"log"
	"os"
	"os/exec"
	"syscall"

	"github.com/google/go-tpm/tpm"
	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"golang.org/x/crypto/ed25519"
)

const (
	tpmDevice  string = "/dev/tpm0"
	mountPath  string = "/mnt/vboot"
	filesystem string = "ext3"
)

var (
	publicKey            *string
	pcr                  *uint
	bootDev              *string
	linuxKernel          *string
	linuxKernelSignature *string
	initrd               *string
	initrdSignature      *string
	debug                *bool
	noTPM                *bool
)

func die(err error) {
	if *debug {
		panic(err)
	}
	if err := syscall.Reboot(syscall.LINUX_REBOOT_CMD_POWER_OFF); err != nil {
		log.Fatalf("reboot err: %v", err)
	}
}

func registeredMain() {
	flag.Parse()

	if err := os.MkdirAll(mountPath, os.ModePerm); err != nil {
		die(err)
	}

	if err := syscall.Mount(*bootDev, mountPath, filesystem, syscall.MS_RDONLY, ""); err != nil {
		die(err)
	}

	paths := []string{*publicKey, *linuxKernel, *linuxKernelSignature, *initrd, *initrdSignature}
	files := make(map[string][]byte)

	for _, element := range paths {
		data, err := os.ReadFile(element)
		if err != nil {
			die(err)
		} else {
			files[element] = data
		}
	}

	kernelDigest := sha256.Sum256(files[*linuxKernel])
	initrdDigest := sha256.Sum256(files[*initrd])

	pcrDigestKernel := sha1.Sum(files[*linuxKernel])
	pcrDigestInitrd := sha1.Sum(files[*initrd])

	kernelSuccess := ed25519.Verify(files[*publicKey], kernelDigest[:], files[*linuxKernelSignature])
	initrdSuccess := ed25519.Verify(files[*publicKey], initrdDigest[:], files[*initrdSignature])

	if !kernelSuccess || !initrdSuccess {
		die(nil)
	}

	if !*noTPM {
		rwc, err := tpm.OpenTPM(tpmDevice)
		if err != nil {
			die(err)
		}

		tpm.PcrExtend(rwc, uint32(*pcr), pcrDigestKernel)
		tpm.PcrExtend(rwc, uint32(*pcr), pcrDigestInitrd)
	}

	binary, lookErr := exec.LookPath("kexec")
	if lookErr != nil {
		die(lookErr)
	}

	args := []string{"kexec", "-initrd", *initrd, *linuxKernel}
	env := os.Environ()

	if execErr := syscall.Exec(binary, args, env); execErr != nil {
		die(execErr)
	}
}
func busyboxInit1() {
	publicKey = flag.String("pubkey", "/etc/sig.pub", "A public key which should verify the signature.")
}
func busyboxInit2() {
	pcr = flag.Uint("pcr", 12, "The pcr index used for measuring the kernel before kexec.")
}
func busyboxInit3() {
	bootDev = flag.String("boot-device", "/dev/sda1", "The boot device which is used to kexec into a signed kernel.")
}
func busyboxInit4() {
	linuxKernel = flag.String("kernel", "/mnt/vboot/kernel", "Kernel image file path.")
}
func busyboxInit5() {
	linuxKernelSignature = flag.String("kernel-sig", "/mnt/vboot/kernel.sig", "Kernel image signature file path.")
}
func busyboxInit6() {
	initrd = flag.String("initrd", "/mnt/vboot/initrd", "Initrd file path.")
}
func busyboxInit7() {
	initrdSignature = flag.String("initrd-sig", "/mnt/vboot/initrd.sig", "Initrd signature file path.")
}
func busyboxInit8() {
	debug = flag.Bool("debug", false, "Enables debug mode.")
}
func busyboxInit9() {
	noTPM = flag.Bool("no-tpm", false, "Disables tpm measuring process.")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
	busyboxInit5()
	busyboxInit6()
	busyboxInit7()
	busyboxInit8()
	busyboxInit9()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("vboot", registeredInit, registeredMain)
}
