// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// losetup sets up and controls loop devices.
//
// Synopsis:
//
//	losetup [-Ad] FILE
//	losetup [-Ad] DEV FILE
//
// Options:
//
//	-A: pick any device
//	-d: detach the device
package bblosetup

import (
	"flag"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/mount/loop"
)

var detach *bool

func registeredMain() {
	var (
		filename, devicename string
		err                  error
	)

	flag.Parse()
	args := flag.Args()
	if *detach {
		if len(args) == 1 {
			if err := loop.ClearFile(args[0]); err != nil {
				log.Fatal("Error clearing device: ", err)
			}
			log.Println("Detached", args[0])
			os.Exit(0)
		}
		flag.Usage()
		log.Fatal("Syntax Error")
	}

	if len(args) == 1 {
		devicename, err = loop.FindDevice()
		if err != nil {
			log.Fatalf("can't find a loop: %v", err)
		}
		filename = args[0]
	} else if len(args) == 2 {
		devicename = args[0]
		filename = args[1]
	} else {
		flag.Usage()
		log.Fatal("Syntax Error")
	}

	if err := loop.SetFile(devicename, filename); err != nil {
		log.Fatal("Could not set loop device:", err)
	}

	log.Printf("Attached %s to %s", devicename, filename)
}
func busyboxInit1() {
	detach = flag.Bool("d", false, "Detach the device")
}
func busyboxInit0() {
	busyboxInit1()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("losetup", registeredInit, registeredMain)
}
