// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !darwin && !dragonfly && !freebsd && !linux && !nacl && !netbsd && !openbsd && !solaris && windows

// Copyright 2016-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbwhich

func canExecute(path string) bool {
	return true
}
