// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !tinygo || tinygo.enable

// Copyright 2014-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Serve files on the network.
//
// Synopsis:
//
//	srvfiles [--h=HOST] [--p=PORT] [--d=DIR]
//
// Options:
//
//	--h: hostname (default: 127.0.0.1)
//	--p: port number (default: 8080)
//	--d: directory to serve (default: .)
package bbsrvfiles

import (
	"flag"
	"log"
	"net"
	"net/http"

	// To build the dependencies of this package with TinyGo, we need to include
	// the cpuid package, since tinygo does not support the asm code in the
	// cpuid package. The cpuid package will use the tinygo bridge to get the
	// CPU information. For further information see
	// github.com/u-root/cpuid/cpuid_amd64_tinygo_bridge.go
	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	_ "github.com/u-root/cpuid"
)

var (
	host *string
	port *string
	dir  *string
)

var cacheHeaders []string

func maxAgeHandler(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		for _, v := range cacheHeaders {
			if r.Header.Get(v) != "" {
				r.Header.Del(v)
			}
		}

		h.ServeHTTP(w, r)
	})
}

func registeredMain() {
	flag.Parse()
	http.Handle("/", maxAgeHandler(http.FileServer(http.Dir(*dir))))
	log.Fatal(http.ListenAndServe(net.JoinHostPort(*host, *port), nil))
}
func busyboxInit1() {
	host = flag.String("h", "127.0.0.1", "hostname")
}
func busyboxInit2() {
	port = flag.String("p", "8080", "port number")
}
func busyboxInit3() {
	dir = flag.String("d", ".", "directory to serve")
}
func busyboxInit4() {

	cacheHeaders = []string{
		"ETag",
		"If-Modified-Since",
		"If-None-Match",
		"If-Range",
		"If-Unmodified-Since",
	}
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("srvfiles", registeredInit, registeredMain)
}
