// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2012 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// our first builtin: cd
package bbrush

import (
	"errors"
	"os"
)

var errCdUsage error

func busyboxInit2() {
	_ = addBuiltIn("cd", cd)
}

func cd(c *Command) error {
	if len(c.argv) != 1 {
		return errCdUsage
	}

	err := os.Chdir(c.argv[0])
	return err
}
func busyboxInit1() {
	errCdUsage = errors.New("usage: cd one-path")
}
