// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !plan9 && !windows && (darwin || linux)

// Copyright 2013-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// mkfifo creates a named pipe.
//
// Synopsis:
//
//	mkfifo [OPTIONS] NAME...
//
// Options:
//
//	-m: mode (default 0600)
package bbmkfifo

import (
	"flag"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"golang.org/x/sys/unix"
)

const (
	defaultMode = 0o660 | unix.S_IFIFO
	cmd         = "mkfifo [-m] NAME..."
)

var mode *int

func busyboxInit2() {
	defUsage := flag.Usage
	flag.Usage = func() {
		os.Args[0] = cmd
		defUsage()
	}
}

func registeredMain() {
	flag.Parse()

	if flag.NArg() < 1 {
		log.Fatal("please provide a path, or multiple, to create a fifo")
	}

	for _, path := range flag.Args() {
		if err := unix.Mkfifo(path, uint32(*mode)); err != nil {
			log.Fatalf("Error while creating fifo, %v", err)
		}
	}
}
func busyboxInit1() {
	mode = flag.Int("mode", defaultMode, "Mode to create fifo")
}
func busyboxInit0() {
	busyboxInit1()
}
func registeredInit() {
	busyboxInit0()
	busyboxInit2()
}
func init() {
	bbmain.Register("mkfifo", registeredInit, registeredMain)
}
