// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2019 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// hwclock reads or changes the hardware clock (RTC) in UTC format.
//
// Synopsis:
//
//	hwclock [-w]
//
// Description:
//
//	It prints the current hwclock time in UTC if called without any flags.
//	It sets the hwclock to the system clock in UTC if called with -w.
//
// Options:
//
//	-w: set hwclock to system clock in UTC
package bbhwclock

import (
	"flag"
	"fmt"
	"log"
	"time"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/rtc"
)

var write *bool

func registeredMain() {
	flag.Parse()

	r, err := rtc.OpenRTC()
	if err != nil {
		log.Fatal(err)
	}
	defer r.Close()

	if *write {
		tu := time.Now().UTC()
		if err := r.Set(tu); err != nil {
			log.Fatal(err)
		}
	}

	t, err := r.Read()
	if err != nil {
		log.Fatal(err)
	}

	// Print local time. Match the format of util-linux' hwclock.
	fmt.Println(t.Local().Format("Mon 2 Jan 2006 15:04:05 AM MST"))
}
func busyboxInit1() {
	write = flag.Bool("w", false, "Set hwclock from system clock in UTC")
}
func busyboxInit0() {
	busyboxInit1()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("hwclock", registeredInit, registeredMain)
}
