// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2019 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// zimage dumps the header of a zImage.
//
// Synopsis:
//
//	zimage FILE
//
// Description:
//
//	This is mainly for debugging purposes.
package bbzimage

import (
	"fmt"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/boot/zimage"
)

func registeredMain() {
	if len(os.Args) != 2 {
		log.Fatalf("usage: %s FILE", os.Args[0])
	}

	f, err := os.Open(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}

	header, err := zimage.Parse(f)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%#v\n", header)
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("zimage", registeredInit, registeredMain)
}
