// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Remove a module from the Linux kernel
//
// Synopsis:
//
//	rmmod name
//
// Description:
//
//	rmmod is a clone of rmmod(8)
//
// Author:
//
//	Roland Kammerer <dev.rck@gmail.com>
package bbrmmod

import (
	"log"
	"os"
	"syscall"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/kmodule"
)

func registeredMain() {
	if len(os.Args) < 2 {
		log.Fatalf("rmmod: ERROR: missing module name.\n")
	}

	for _, modname := range os.Args[1:] {
		if err := kmodule.Delete(modname, syscall.O_NONBLOCK); err != nil {
			log.Fatalf("rmmod: %v", err)
		}
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("rmmod", registeredInit, registeredMain)
}
