// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build (!tinygo || tinygo.enable) && linux

// Copyright 2012-2023 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbnetcat

import "github.com/u-root/u-root/pkg/netcat"

func busyboxInit2() {
	osConnectors[netcat.SOCKET_TYPE_SCTP] = connectToSCTPSocket
}
