// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2020 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// acpicat cats ACPI tables from the kernel.
// The default method is "files", commonly provided in Linux via /sys.
// Other methods are available depending on the platform.
// Further selection of which tables are used can be done with acpigrep.
package bbacpicat

import (
	"flag"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/acpi"
)

var (
	source *string
	debug  *bool
)

func registeredMain() {
	flag.Parse()
	if *debug {
		acpi.Debug = log.Printf
	}
	t, err := acpi.ReadTables(*source)
	if err != nil {
		log.Fatal(err)
	}
	if len(t) == 0 {
		log.Fatalf("%s: no tables read", *source)
	}
	if err := acpi.WriteTables(os.Stdout, t[0], t[1:]...); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit1() {
	source = flag.String("s", acpi.DefaultMethod, "source of the tables")
}
func busyboxInit2() {
	debug = flag.Bool("d", false, "Enable debug prints")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("acpicat", registeredInit, registeredMain)
}
