// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux && linux

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbswitch_root

import (
	"flag"
	"fmt"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/mount"
)

var (
	help    *bool
	version *bool
)

func usage() string {
	return "switch_root [-h] [-V]\nswitch_root newroot init"
}

func registeredMain() {
	flag.Parse()

	if len(flag.Args()) == 0 {
		fmt.Println(usage())
		os.Exit(0)
	}

	if *help {
		fmt.Println(usage())
		os.Exit(0)
	}

	if *version {
		fmt.Println("Version XX")
		os.Exit(0)
	}

	newRoot := flag.Args()[0]
	init := flag.Args()[1]

	if err := mount.SwitchRoot(newRoot, init); err != nil {
		log.Fatalf("switch_root failed %v\n", err)
	}
}
func busyboxInit1() {
	help = flag.Bool("h", false, "Help")
}
func busyboxInit2() {
	version = flag.Bool("V", false, "Version")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("switch_root", registeredInit, registeredMain)
}
