// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2013-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// modprobe - Add and remove modules from the Linux Kernel
//
// Synopsis:
//
//	modprobe [-n] modulename [parameters...]
//	modprobe [-n] -a modulename...
//
// Author:
//
//	Roland Kammerer <dev.rck@gmail.com>
package bbmodprobe

import (
	"flag"
	"log"
	"os"
	"strings"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/kmodule"
)

const cmd = "modprobe [-an] modulename[s] [parameters...]"

var (
	dryRun     *bool
	all        *bool
	verboseAll *bool
	rootDir    *string
	kernelVer  *string
)

func busyboxInit6() {
	defUsage := flag.Usage
	flag.Usage = func() {
		os.Args[0] = cmd
		defUsage()
	}
}

func registeredMain() {
	flag.Parse()

	if flag.NArg() == 0 {
		log.Println("Usage: ERROR: one module and optional module options.")
		flag.Usage()
		os.Exit(1)
	}

	opts := kmodule.ProbeOpts{
		RootDir: *rootDir,
		KVer:    *kernelVer,
	}
	if *dryRun {
		log.Println("Unique dependencies in load order, already loaded ones get skipped:")
		opts.DryRunCB = func(modPath string) {
			log.Println(modPath)
		}
	}

	// -va is just an alias for -a
	*all = *all || *verboseAll
	if *all {
		modNames := flag.Args()
		for _, modName := range modNames {
			if err := kmodule.ProbeOptions(modName, "", opts); err != nil {
				log.Printf("modprobe: Could not load module %q: %v", modName, err)
			}
		}
		os.Exit(0)
	}

	modName := flag.Args()[0]
	modOptions := strings.Join(flag.Args()[1:], " ")

	if err := kmodule.ProbeOptions(modName, modOptions, opts); err != nil {
		log.Fatalf("modprobe: Could not load module %q: %v", modName, err)
	}
}
func busyboxInit1() {
	dryRun = flag.Bool("n", false, "Dry run")
}
func busyboxInit2() {
	all = flag.Bool("a", false, "Insert all module names on the command line.")
}
func busyboxInit3() {
	verboseAll = flag.Bool("va", false, "Insert all module names on the command line.")
}
func busyboxInit4() {
	rootDir = flag.String("d", "/", "Root directory for modules")
}
func busyboxInit5() {
	kernelVer = flag.String("S", "", "Set kernel version instead of using uname")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
	busyboxInit5()
}
func registeredInit() {
	busyboxInit0()
	busyboxInit6()
}
func init() {
	bbmain.Register("modprobe", registeredInit, registeredMain)
}
