//go:build ignore

// generate writes the built-in shell's commands: every command in u-root
// (github.com/u-root/u-root/cmds) that builds for an operating system tunneld
// ships to, rewritten from a program into a package that registers itself,
// under internal/, and zz_commands_<os>.go, which links each operating
// system's. Every file it writes is named zz_, so a listing puts what is
// written by hand first and what is generated after it.
//
// u-root's commands are programs — package main — and a program cannot be
// imported. gobusybox, u-root's own busybox builder, rewrites one into a
// package whose main and init run only when the command is asked for by name
// (internal/bbmain); this keeps what it writes rather than building it.
//
// The rewrite is made for one GOOS and GOARCH at a time, since it reads the
// files a build would. A command goes in for an operating system when it
// builds on both of that system's architectures and both rewrites agree; its
// package is shared, with a //go:build line naming its systems, when every
// system's rewrite agrees too, and one package per system when they do not.
// What does not build anywhere is left out, and the run says so; so is what
// leftOut names.
//
// The u-root it reads is the one go.mod requires. Run from this directory:
//
//	go generate
package main

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/build/constraint"
	"go/format"
	"io/fs"
	"log"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"strings"
	"sync"
)

const (
	// makebb is gobusybox's generator, pinned.
	makebb = "github.com/u-root/gobusybox/src/cmd/makebb@v0.3.0"
	uroot  = "github.com/u-root/u-root"
	// bbmainPath is what the rewrite imports; bbmain is where it goes.
	bbmainPath = "bb.u-root.com/bb/pkg/bbmain"
	self       = "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin"
	bbmain     = self + "/internal/bbmain"
)

// leftOut are commands that build but are not brought, and why.
var leftOut = map[string]string{
	// Its line editor's terminal reader, github.com/mattn/go-localereader,
	// carries no license notice for THIRD_PARTY_LICENSES (make licenses), and
	// the built-in shell is Elvish already.
	"cmds/core/gosh": "a second shell, whose dependencies carry no license notice",
}

// oses and arches are the platforms tunneld ships (the Makefile's PLATFORMS).
var (
	oses   = []string{"darwin", "linux", "windows"}
	arches = []string{"amd64", "arm64"}
)

type target struct{ goos, goarch string }

func (t target) String() string { return t.goos + "/" + t.goarch }

// files is one command's rewritten package: file name to contents.
type files map[string][]byte

func main() {
	log.SetFlags(0)
	log.SetPrefix("generate: ")
	ctx := context.Background()

	version := strings.TrimSpace(run(ctx, "", nil, "go", "list", "-m", "-f", "{{.Version}}", uroot))
	src := strings.TrimSpace(run(ctx, "", nil, "go", "list", "-m", "-f", "{{.Dir}}", uroot))
	work, err := os.MkdirTemp("", "tunneld-generate-")
	check(err)
	defer func() { _ = os.RemoveAll(work) }()

	// The module cache is read-only, and the build and the rewrite both want
	// to write beside the source.
	tree := filepath.Join(work, "u-root")
	check(copyTree(src, tree))
	bin := filepath.Join(work, "bin")
	run(ctx, "", []string{"GOBIN=" + bin}, "go", "install", makebb)

	candidates, err := filepath.Glob(filepath.Join(tree, "cmds", "*", "*"))
	check(err)
	var cmds []string
	for _, dir := range candidates {
		if gos, _ := filepath.Glob(filepath.Join(dir, "*.go")); len(gos) > 0 {
			rel, _ := filepath.Rel(tree, dir)
			cmds = append(cmds, filepath.ToSlash(rel))
		}
	}
	cmds = slices.DeleteFunc(cmds, func(cmd string) bool {
		if why, ok := leftOut[cmd]; ok {
			log.Printf("%s: left out, %s", cmd, why)
			return true
		}
		return false
	})
	log.Printf("u-root %s: %d commands", version, len(cmds))

	// rewritten[cmd][target] is the command's package as rewritten for target.
	rewritten := map[string]map[target]files{}
	var bbmainSrc []byte
	for _, goos := range oses {
		for _, goarch := range arches {
			t := target{goos, goarch}
			built := builds(ctx, tree, t, cmds)
			out := filepath.Join(work, "gen-"+goos+"-"+goarch)
			pkgs := rewrite(ctx, tree, filepath.Join(bin, "makebb"), out, t, built)
			log.Printf("%s: %d build, %d rewritten", t, len(built), len(pkgs))
			for cmd, fs := range pkgs {
				if rewritten[cmd] == nil {
					rewritten[cmd] = map[target]files{}
				}
				rewritten[cmd][t] = fs
			}
			if bbmainSrc == nil {
				bbmainSrc, err = os.ReadFile(filepath.Join(out, "src", filepath.FromSlash(bbmainPath), "register.go"))
				check(err)
			}
		}
	}

	internal := "internal"
	check(os.RemoveAll(internal))
	header := fmt.Sprintf("// Code generated by generate.go from %s %s; DO NOT EDIT.\n\n", uroot, version)
	write(filepath.Join(internal, "bbmain", "zz_register.go"), header, "", bbmainSrc)

	// imports[goos] are the packages commands_<goos>.go links.
	imports := map[string][]string{}
	var missing []string
	for _, cmd := range slices.Sorted(maps.Keys(rewritten)) {
		per := rewritten[cmd]
		// bySystem[goos] is the rewrite for goos, when both its
		// architectures built the command and rewrote it alike.
		bySystem := map[string]files{}
		for _, goos := range oses {
			a, b := per[target{goos, "amd64"}], per[target{goos, "arm64"}]
			switch {
			case a == nil || b == nil:
			case !same(a, b):
				log.Printf("%s: the %s rewrites differ by architecture; left out there", cmd, goos)
			default:
				bySystem[goos] = a
			}
		}
		if len(bySystem) == 0 {
			missing = append(missing, cmd)
			continue
		}
		dir := filepath.Join(internal, filepath.FromSlash(strings.TrimPrefix(cmd, "cmds/")))
		systems := slices.Sorted(maps.Keys(bySystem))
		first := bySystem[systems[0]]
		shared := true
		for _, goos := range systems[1:] {
			shared = shared && same(first, bySystem[goos])
		}
		if shared {
			tag := ""
			if len(systems) < len(oses) {
				tag = strings.Join(systems, " || ")
			}
			writePackage(dir, header, tag, first)
			for _, goos := range systems {
				imports[goos] = append(imports[goos], filepath.ToSlash(dir))
			}
			continue
		}
		for _, goos := range systems {
			sub := filepath.Join(dir, goos)
			writePackage(sub, header, goos, bySystem[goos])
			imports[goos] = append(imports[goos], filepath.ToSlash(sub))
		}
	}

	for _, goos := range oses {
		var b strings.Builder
		b.WriteString(header)
		fmt.Fprintf(&b, "package builtin\n\n// The commands the built-in shell brings on %s.\nimport (\n", goos)
		for _, pkg := range imports[goos] {
			fmt.Fprintf(&b, "\t_ %q\n", self+"/"+pkg)
		}
		b.WriteString(")\n")
		out, err := format.Source([]byte(b.String()))
		check(err)
		check(os.WriteFile("zz_commands_"+goos+".go", out, 0o644))
		log.Printf("zz_commands_%s.go: %d commands", goos, len(imports[goos]))
	}
	if len(missing) > 0 {
		log.Printf("left out, building nowhere tunneld ships: %s", strings.Join(missing, " "))
	}
}

// builds answers which of cmds build for t, building each on its own so that
// one that does not cannot hide the rest.
func builds(ctx context.Context, tree string, t target, cmds []string) []string {
	ok := make([]bool, len(cmds))
	sem := make(chan struct{}, runtime.NumCPU())
	var wg sync.WaitGroup
	for i, cmd := range cmds {
		wg.Add(1)
		sem <- struct{}{}
		go func() {
			defer func() { <-sem; wg.Done() }()
			c := exec.CommandContext(ctx, "go", "build", "-o", os.DevNull, "./"+cmd)
			c.Dir = tree
			c.Env = append(os.Environ(), "GOOS="+t.goos, "GOARCH="+t.goarch, "CGO_ENABLED=0")
			ok[i] = c.Run() == nil
		}()
	}
	wg.Wait()
	var built []string
	for i, cmd := range cmds {
		if ok[i] {
			built = append(built, cmd)
		}
	}
	return built
}

// failedPackage is how makebb names a command it could not rewrite.
var failedPackage = regexp.MustCompile(`failed to add package ` + regexp.QuoteMeta(uroot) + `/(\S+) `)

// rewrite runs makebb over cmds for t and answers each command's rewritten
// package. A command makebb cannot load is dropped and the rest tried again.
func rewrite(ctx context.Context, tree, makebb, out string, t target, cmds []string) map[string]files {
	for {
		_ = os.RemoveAll(out)
		args := append([]string{"-g", "-gen-dir", out}, prefixed(cmds)...)
		c := exec.CommandContext(ctx, makebb, args...)
		c.Dir = tree
		c.Env = append(os.Environ(), "GOOS="+t.goos, "GOARCH="+t.goarch, "CGO_ENABLED=0")
		output, err := c.CombinedOutput()
		if err == nil {
			break
		}
		m := failedPackage.FindSubmatch(output)
		if m == nil || !slices.Contains(cmds, string(m[1])) {
			log.Fatalf("makebb for %s: %v\n%s", t, err, output)
		}
		log.Printf("%s: %s does not rewrite; left out", t, m[1])
		cmds = slices.DeleteFunc(cmds, func(c string) bool { return c == string(m[1]) })
	}
	pkgs := map[string]files{}
	for _, cmd := range cmds {
		dir := filepath.Join(out, "src", filepath.FromSlash(uroot), filepath.FromSlash(cmd))
		entries, err := os.ReadDir(dir)
		if errors.Is(err, fs.ErrNotExist) {
			// Skipped by makebb: build constraints exclude every file.
			continue
		}
		check(err)
		fs := files{}
		for _, e := range entries {
			if e.Type().IsRegular() && !strings.HasSuffix(e.Name(), "_test.go") {
				b, err := os.ReadFile(filepath.Join(dir, e.Name()))
				check(err)
				fs[e.Name()] = b
			}
		}
		if len(fs) > 0 {
			pkgs[cmd] = fs
		}
	}
	return pkgs
}

func prefixed(cmds []string) []string {
	out := make([]string, len(cmds))
	for i, c := range cmds {
		out[i] = "./" + c
	}
	return out
}

func same(a, b files) bool {
	return maps.EqualFunc(a, b, bytes.Equal)
}

func writePackage(dir, header, tag string, fs files) {
	for name, b := range fs {
		write(filepath.Join(dir, "zz_"+name), header, tag, b)
	}
}

// write writes one rewritten file: bbmain's import pointed at ours, the
// generated header, and tag (a //go:build expression, or none) joined with
// whatever constraint the file already carries.
func write(path, header, tag string, src []byte) {
	check(os.MkdirAll(filepath.Dir(path), 0o755))
	if !strings.HasSuffix(path, ".go") {
		check(os.WriteFile(path, src, 0o644))
		return
	}
	src = bytes.ReplaceAll(src, []byte(`"`+bbmainPath+`"`), []byte(`"`+bbmain+`"`))
	var existing constraint.Expr
	var kept []string
	for _, line := range strings.SplitAfter(string(src), "\n") {
		trimmed := strings.TrimSpace(line)
		if constraint.IsGoBuild(trimmed) {
			e, err := constraint.Parse(trimmed)
			check(err)
			existing = e
			continue
		}
		if constraint.IsPlusBuild(trimmed) {
			continue
		}
		kept = append(kept, line)
	}
	var expr constraint.Expr = existing
	if tag != "" {
		ours, err := constraint.Parse("//go:build " + tag)
		check(err)
		if expr == nil {
			expr = ours
		} else {
			expr = &constraint.AndExpr{X: existing, Y: ours}
		}
	}
	var b strings.Builder
	b.WriteString(header)
	if expr != nil {
		fmt.Fprintf(&b, "//go:build %s\n\n", expr)
	}
	b.WriteString(strings.Join(kept, ""))
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatalf("%s: %v", path, err)
	}
	check(os.WriteFile(path, out, 0o644))
}

// copyTree copies src to dst, writable.
func copyTree(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, path)
		to := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(to, 0o755)
		}
		if !d.Type().IsRegular() {
			return nil
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(to, b, 0o644)
	})
}

func run(ctx context.Context, dir string, env []string, name string, args ...string) string {
	c := exec.CommandContext(ctx, name, args...)
	c.Dir = dir
	c.Env = append(os.Environ(), env...)
	c.Stderr = os.Stderr
	out, err := c.Output()
	if err != nil {
		log.Fatalf("%s %s: %v", name, strings.Join(args, " "), err)
	}
	return string(out)
}

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
