// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2020 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// partprobe prompts the OS to re-read partition tables.
//
// Synopsis:
//
//	partprobe [device]...
package bbpartprobe

import (
	"flag"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/mount/block"
)

func registeredMain() {
	flag.Parse()

	devs := flag.Args()

	if len(devs) == 0 {
		log.Printf("Usage: partprobe [device]...")
		os.Exit(0)
	}

	for _, dev := range devs {
		d, err := block.Device(dev)
		if err != nil {
			log.Printf("Failed to find device %s: %v", dev, err)
			continue
		}

		if err := d.ReadPartitionTable(); err != nil {
			log.Printf("Failed to read partition table for %s: %v", dev, err)
		}
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("partprobe", registeredInit, registeredMain)
}
