// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Print name of current directory.
//
// Synopsis:
//
//	pwd [-LP]
//
// Options:
//
//	-P: don't follow symlinks
//
// Author:
//
//	created by Beletti (rhiguita@gmail.com)
package bbpwd

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

var (
	// This is the default. Setting it to false doesn't do anything in GNU
	// or zsh pwd, because you just can't even set it to false.
	_ *bool

	physical *bool
)

func pwd(followSymlinks bool) (string, error) {
	path, err := os.Getwd()
	if err == nil && followSymlinks {
		path, err = filepath.EvalSymlinks(path)
	}
	return path, err
}

func registeredMain() {
	flag.Parse()

	path, err := pwd(*physical)
	if err != nil {
		log.Fatalf("%v", err)
	}
	fmt.Println(path)
}
func busyboxInit1() {
	_ = flag.Bool("L", true, "don't follow any symlinks")
}
func busyboxInit2() {

	physical = flag.Bool("P", false, "follow all symlinks (avoid all symlinks)")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("pwd", registeredInit, registeredMain)
}
