// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbdd

import "syscall"

func busyboxInit4() {
	flagMap["dsync"] = bitClearAndSet{set: syscall.O_DSYNC}
	allowedFlags |= syscall.O_DSYNC
}
