// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2020 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Blkid prints information about blocks.
package bbblkid

import (
	"fmt"
	"io"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/mount/block"
)

func run(getBlock func() (block.BlockDevices, error), out io.Writer) error {
	devices, err := getBlock()
	if err != nil {
		return fmt.Errorf("error getting Block devices: %w", err)
	}

	for _, device := range devices {
		fmt.Fprint(out, device.DevicePath())
		if device.FsUUID != "" {
			fmt.Fprintf(out, " UUID=%q", device.FsUUID)
		}
		if device.FSType != "" {
			fmt.Fprintf(out, " TYPE=%q", device.FSType)
		}
		fmt.Fprintln(out)
	}
	return nil
}

func registeredMain() {
	if err := run(block.GetBlockDevices, os.Stdout); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("blkid", registeredInit, registeredMain)
}
