// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !plan9 && !windows && linux

// Copyright 2016-2020 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// sync command in Go.
//
// Synopsis:
//		sync [-df] [FILE]
//

package bbsync

import (
	"flag"
	"log"
	"os"
	"syscall"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/uroot/util"
)

var (
	data       *bool
	filesystem *bool
)

var usage string

func busyboxInit4() {
	flag.Usage = util.Usage(flag.Usage, usage)
}

func doSyscall(syscallNum uintptr, args []string) error {
	for _, fileName := range args {
		f, err := os.OpenFile(fileName, syscall.O_RDONLY|syscall.O_NOCTTY|syscall.O_CLOEXEC, 0o644)
		if err != nil {
			return err
		}
		if _, _, err = syscall.Syscall(syscallNum, uintptr(f.Fd()), 0, 0); err.(syscall.Errno) != 0 {
			return err
		}
		f.Close()
	}
	return nil
}

func registeredMain() {
	flag.Parse()
	if err := sync(*data, *filesystem, flag.Args()); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit1() {
	data = flag.Bool("data", false, "sync file data, no metadata")
}
func busyboxInit2() {
	filesystem = flag.Bool("filesystem", false, "commit filesystem caches to disk")
}
func busyboxInit3() {

	usage = "Usage: %s [OPTION] [FILE]...\n"
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
}
func registeredInit() {
	busyboxInit0()
	busyboxInit4()
}
func init() {
	bbmain.Register("sync", registeredInit, registeredMain)
}
