// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2023 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
package bbsync

import (
	"syscall"

	"golang.org/x/sys/unix"
)

func sync(data, filesystem bool, args []string) error {
	switch {
	case data:
		return doSyscall(unix.SYS_FDATASYNC, args)
	case filesystem:
		return doSyscall(unix.SYS_SYNCFS, args)
	default:
		syscall.Sync()
		return nil
	}
}
