// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2022 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// poweroff turns the system off, without delay. There are no options.
//
// Synopsis:
//
//	poweroff
//
// Description:
//
//	poweroff calls the kernel to power off the systems.
package bbpoweroff

import (
	"log"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"golang.org/x/sys/unix"
)

func registeredMain() {
	if err := unix.Reboot(unix.LINUX_REBOOT_CMD_POWER_OFF); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("poweroff", registeredInit, registeredMain)
}
