// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbumount

import (
	"errors"
	"flag"

	"github.com/u-root/u-root/pkg/mount"
)

var (
	force *bool
	lazy  *bool
)

func umount() error {
	flag.Parse()
	a := flag.Args()
	if len(a) != 1 {
		return errors.New("usage: umount [-f | -l] path")
	}
	path := a[0]
	return mount.Unmount(path, *force, *lazy)
}
func busyboxInit1() {
	force = flag.Bool("f", false, "Force unmount")
}
func busyboxInit2() {
	lazy = flag.Bool("l", false, "Lazy unmount")
}
