// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !plan9 && !windows && linux

// Copyright 2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Unmount a filesystem at the specified path.
//
// Synopsis:
//
//	umount [-f | -l] PATH
//
// Options:
//
//	-f: force unmount
//	-l: lazy unmount
package bbumount

import (
	"log"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

func registeredMain() {
	if err := umount(); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("umount", registeredInit, registeredMain)
}
