// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !test && !windows && darwin

// Copyright 2012-2022 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Run a command and kill it if it runs more than a specified duration
//
// Synopsis:
//	timeout [-t duration-string] command [args...]
//
// Description:
//	timeout will run the command until it succeeds or too much time has passed.
//	The default timeout is 30s.
//	If no args are given, it will print a usage error.
//
// Example:
//	$ timeout echo hi
//	hi
//	$
//	$./timeout -t 5s bash -c 'sleep 40'
//	$ 2022/03/31 14:47:32 signal: killed
//	$./timeout  -t 5s bash -c 'sleep 40'
//	$ 2022/03/31 14:47:40 signal: killed
//	$./timeout  -t 5s bash -c 'sleep 1'
//	$

package bbtimeout

import (
	"errors"
	"flag"
	"log"
	"os"
	"time"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

type cmd struct {
	args         []string
	timeout      time.Duration
	signal       string
	in, out, err *os.File
}

var (
	timeout   *time.Duration
	signal    *string
	errNoArgs error
)

func registeredMain() {
	flag.Parse()
	c := &cmd{args: flag.Args(), in: os.Stdin, out: os.Stdout, err: os.Stderr, timeout: *timeout, signal: *signal}
	if errno, err := c.run(); err != nil || errno != 0 {
		log.Printf("timeout(%v):%v", *timeout, err)
		os.Exit(errno)
	}
}
func busyboxInit2() {
	timeout = flag.Duration("t", 30*time.Second, "Timeout for command")
}
func busyboxInit3() {
	signal = flag.String("signal", "TERM", "specify the signal to be sent on timeout")
}
func busyboxInit4() {
	errNoArgs = errors.New("need at least a command to run")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("timeout", registeredInit, registeredMain)
}
