// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2015-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Print ansi escape sequences.
//
// Synopsis:
//
//	ansi COMMAND
//
// Options:
//
//	COMMAND must be one of:
//	    - clear: clear the screen and reset the cursor position
//
// Author:
//
//	Manoel Vilela <manoel_vilela@engineer.com>
package bbansi

import (
	"fmt"
	"io"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

// using ansi escape codes /033 => escape code
// The "\033[1;1H" part moves the cursor to position (1,1)
// "\033[2J" part clears the screen.
// if you wants add more escape codes, append on map below
// arg:escape_code
var commands map[string]string

func ansi(w io.Writer, args []string) error {
	for _, arg := range args {
		c, ok := commands[arg]
		if !ok {
			return fmt.Errorf("command ANSI %q don't exists", arg)
		}
		fmt.Fprint(w, c)
	}
	return nil
}

func registeredMain() {
	if err := ansi(os.Stdout, os.Args[1:]); err != nil {
		log.Fatalf("%v", err)
	}
}
func busyboxInit1() {
	commands = map[string]string{
		"clear": "\033[1;1H\033[2J",
	}
}
func busyboxInit0() {
	busyboxInit1()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("ansi", registeredInit, registeredMain)
}
