// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !plan9 && !windows && darwin

// Copyright 2024 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbkill

import "fmt"

func siglist() (s string) {
	for i, sig := range signames {
		s = s + fmt.Sprintf("%d: %v\n", i, sig)
	}
	return
}
