// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// gzip compresses files using gzip compression.
package bbgzip

import (
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/core/gzip"
)

func registeredMain() {
	program, args := os.Args[0], os.Args[1:]
	cmd := gzip.New(program)
	if err := cmd.Run(args...); err != nil {
		log.Fatalf("%s: %v", program, err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("gzip", registeredInit, registeredMain)
}
