// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// insmod inserts a module into the running Linux kernel.
//
// Synopsis:
//
//	insmod [filename] [module options...]
//
// Description:
//
//	insmod is a clone of insmod(8)
package bbinsmod

import (
	"log"
	"os"
	"strings"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/kmodule"
)

func registeredMain() {
	if len(os.Args) < 2 {
		log.Fatalf("insmod: ERROR: missing filename.\n")
	}

	// get filename from argv[1]
	filename := os.Args[1]

	// Everything else is module options
	options := strings.Join(os.Args[2:], " ")

	f, err := os.Open(filename)
	if err != nil {
		log.Fatalf("could not open %q: %v", filename, err)
	}
	defer f.Close()

	if err := kmodule.FileInit(f, options, 0); err != nil {
		log.Fatalf("insmod: could not load %q: %v", filename, err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("insmod", registeredInit, registeredMain)
}
