// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2013-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// ls prints the contents of a directory.
//
// Synopsis:
//
//	ls [OPTIONS] [DIRS]...
//
// Options:
//
//	-a: show hidden files
//	-h: show human-readable sizes
//	-d: show directories but not their contents
//	-F: append indicator (, one of */=>@|) to entries
//	-l: long form
//	-Q: quoted
//	-R: equivalent to findutil's find
//	-s: sort by size
//
// Bugs:
//
//	With the `-R` flag, directories are only ever printed once.
package bbls

import (
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/core/ls"
)

func busyboxInit1() {
	log.SetFlags(0)
}

func registeredMain() {
	cmd := ls.New()
	err := cmd.Run(os.Args[1:]...)
	if err != nil {
		log.Fatal("ls: ", err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
	busyboxInit1()
}
func init() {
	bbmain.Register("ls", registeredInit, registeredMain)
}
