// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2022 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// zbi dumps the header of a Zircon boot image.
//
// Synopsis:
//
//	zbi FILE
//
// Description:
//
//	Debugging purposes.
package bbzbi

import (
	"encoding/json"
	"fmt"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/boot/zbi"
)

func registeredMain() {
	if len(os.Args) != 2 {
		log.Fatalf("usage: %s FILE", os.Args[0])
	}

	image, err := zbi.Load(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}

	imageJSON, err := json.MarshalIndent(image, "", "  ")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s\n", string(imageJSON))
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("zbi", registeredInit, registeredMain)
}
