// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build linux && linux

// Copyright 2025 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbpidof

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
)

var errNotFound error

type proc struct {
	comm string
	pid  string
}

func run(stdout io.Writer, procPath string, single, quiet bool, args []string) error {
	procs, err := collect(procPath)
	if err != nil {
		return err
	}

	var pids []string

	for _, proc := range procs {
		for _, arg := range args {
			if proc.comm == arg {
				if single {
					if !quiet {
						fmt.Fprintln(stdout, proc.pid)
					}
					return nil
				}
				pids = append(pids, proc.pid)
			}
		}
	}

	if len(pids) == 0 {
		return errNotFound
	}

	if !quiet {
		fmt.Fprintln(stdout, strings.Join(pids, " "))
	}
	return nil
}

func registeredMain() {
	single := flag.Bool("s", false, "single shot - this instructs the program to only return one pid")
	quiet := flag.Bool("q", false, "do not display matched PIDs to standard out")
	flag.Parse()
	if err := run(os.Stdout, procPath, *single, *quiet, flag.Args()); err != nil {
		if errors.Is(err, errNotFound) {
			os.Exit(1)
		}
		log.Fatal(err)
	}
}
func busyboxInit1() {
	errNotFound = errors.New("pid name not found")
}
func busyboxInit0() {
	busyboxInit1()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("pidof", registeredInit, registeredMain)
}
