// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !plan9 && !windows && (darwin || linux)

// Copyright 2015-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Print build information about the kernel and machine.
//
// Synopsis:
//
//	uname [-asnrvmd]
//
// Options:
//
//	-a: print everything
//	-s: print the kernel name
//	-n: print the network node name
//	-r: print the kernel release
//	-v: print the kernel version
//	-m: print the machine hardware name
package bbuname

import (
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"golang.org/x/sys/unix"
)

var (
	all       *bool
	kernel    *bool
	node      *bool
	release   *bool
	version   *bool
	machine   *bool
	processor *bool
)

type params struct {
	kernel  bool
	node    bool
	release bool
	version bool
	machine bool
}

func handleFlags(u *unix.Utsname, p params) string {
	sysname, nodename := unix.ByteSliceToString(u.Sysname[:]), unix.ByteSliceToString(u.Nodename[:])
	release, version := unix.ByteSliceToString(u.Release[:]), unix.ByteSliceToString(u.Version[:])
	machine := unix.ByteSliceToString(u.Machine[:])
	info := make([]string, 0, 5)

	if p.kernel {
		info = append(info, sysname)
	}
	if p.node {
		info = append(info, nodename)
	}
	if p.release {
		info = append(info, release)
	}
	if p.version {
		info = append(info, version)
	}
	if p.machine {
		info = append(info, machine)
	}

	return strings.Join(info, " ")
}

func run(stdout io.Writer, p params) error {
	var u unix.Utsname
	if err := unix.Uname(&u); err != nil {
		return err
	}
	info := handleFlags(&u, p)
	_, err := fmt.Fprintln(stdout, info)
	return err
}

func parseParams(all, kernel, node, release, version, machine, processor bool) params {
	p := params{
		kernel:  kernel || all,
		node:    node || all,
		release: release || all,
		version: version || all,
		machine: machine || processor || all,
	}

	if !p.kernel && !p.node && !p.release && !p.version && !p.machine {
		p.kernel = true
	}

	return p
}

func registeredMain() {
	flag.Parse()
	p := parseParams(*all, *kernel, *node, *release, *version, *machine, *processor)
	if err := run(os.Stdout, p); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit1() {
	all = flag.Bool("a", false, "print everything")
}
func busyboxInit2() {
	kernel = flag.Bool("s", false, "print the kernel name")
}
func busyboxInit3() {
	node = flag.Bool("n", false, "print the network node name")
}
func busyboxInit4() {
	release = flag.Bool("r", false, "print the kernel release")
}
func busyboxInit5() {
	version = flag.Bool("v", false, "print the kernel version")
}
func busyboxInit6() {
	machine = flag.Bool("m", false, "print the machine hardware name")
}
func busyboxInit7() {
	processor = flag.Bool("p", false, "print the machine hardware name")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
	busyboxInit5()
	busyboxInit6()
	busyboxInit7()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("uname", registeredInit, registeredMain)
}
