// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2016-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// dirname prints out the directory name of one or more args.
// If no arg is given it returns an error and prints a message which,
// per the man page, is incorrect, but per the standard, is correct.
package bbdirname

import (
	"errors"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

var ErrNoArg error

func run(out io.Writer, args []string) error {
	if len(args) < 1 {
		return ErrNoArg
	}

	for _, n := range args {
		fmt.Fprintln(out, filepath.Dir(n))
	}
	return nil
}

func registeredMain() {
	if err := run(os.Stdout, os.Args[1:]); err != nil {
		log.Fatalf("dirname: %v", err)
	}
}
func busyboxInit1() {
	ErrNoArg = errors.New("missing operand")
}
func busyboxInit0() {
	busyboxInit1()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("dirname", registeredInit, registeredMain)
}
