// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// false returns 1.
//
// Synopsis:
//
//	false
//
// Description:
//
//	Command line arguments are ignored.
package bbfalse

import (
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
)

func registeredMain() {
	os.Exit(1)
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("false", registeredInit, registeredMain)
}
