// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build (!tinygo || tinygo.enable) && linux

// Copyright 2017-2019 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbfitboot

import (
	"flag"
	"fmt"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/acpi"
	"github.com/u-root/u-root/pkg/boot"
	"github.com/u-root/u-root/pkg/boot/fit"
	"github.com/u-root/u-root/pkg/vfile"
)

var (
	dryRun     *bool
	debug      *bool
	cmdline    *string
	config     *string
	kernel     *string
	initramfs  *string
	ringPath   *string
	rsdpLookup *bool
)

var v func(string, ...any)

func registeredMain() {
	flag.Parse()

	if *debug {
		v = log.Printf
	}

	if len(flag.Args()) != 1 {
		log.Fatal("Usage: fitboot <file>")
	}
	f, err := fit.New(flag.Args()[0])
	if err != nil {
		log.Fatal(err)
	}

	f.Cmdline, f.Kernel, f.InitRAMFS, f.ConfigOverride = *cmdline, *kernel, *initramfs, *config

	kn, in, err := f.LoadConfig()
	if err == nil {
		f.Kernel, f.InitRAMFS = kn, in
	} else {
		v("Configuration is not available: %v", err)
	}

	if f.Kernel == "" {
		log.Fatal("kernel name is not found in fit configuration or pass through -k.")
	}

	v("Kernel name=%s, initramfs=%s", f.Kernel, f.InitRAMFS)

	kernelCmd := *cmdline
	if *rsdpLookup {
		r, err := acpi.GetRSDP()
		if err != nil {
			log.Fatal("Unable to find acpi table in the environment.")
		}
		v("Found an RSDP at %#x", r.RSDPAddr())
		kernelCmd = fmt.Sprintf("acpi_rsdp=%x %s", r.RSDPAddr(), kernelCmd)
	}

	f.Cmdline = kernelCmd

	if *ringPath != "" {
		ring, err := vfile.GetKeyRing(*ringPath)
		if err != nil {
			log.Fatal(err)
		}
		f.KeyRing = ring
	}

	if err := f.Load(boot.WithVerbose(*debug)); err != nil {
		log.Fatal(err)
	}

	if *dryRun {
		v("Not trying to boot since this is a dry run")
		os.Exit(0)
	}

	if err := boot.Execute(); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit1() {
	dryRun = flag.Bool("dryrun", false, "Do not actually kexec into the boot config")
}
func busyboxInit2() {
	debug = flag.Bool("d", false, "Print debug output")
}
func busyboxInit3() {
	cmdline = flag.String("c", "earlyprintk=ttyS0,115200,keep console=ttyS0", "command line")
}
func busyboxInit4() {
	config = flag.String("config", "", "FIT configuration to use")
}
func busyboxInit5() {
	kernel = flag.String("k", "", "Kernel image node name.")
}
func busyboxInit6() {
	initramfs = flag.String("i", "", "InitRAMFS node name -- default none")
}
func busyboxInit7() {
	ringPath = flag.String("r", "", "Path to PGP keyring. Enforces signature if non-empty path")
}
func busyboxInit8() {
	rsdpLookup = flag.Bool("rsdp", false, "Derrive RSDP table pointer from environment")
}
func busyboxInit9() {

	v = func(string, ...any) {}
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
	busyboxInit5()
	busyboxInit6()
	busyboxInit7()
	busyboxInit8()
	busyboxInit9()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("fitboot", registeredInit, registeredMain)
}
