// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !tinygo

// Copyright 2023 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbtime

import (
	"io"
	"os/exec"
)

func printProcessState(w io.Writer, c *exec.Cmd) {
	if c.ProcessState == nil {
		return
	}
	printTime(w, "user", c.ProcessState.UserTime())
	printTime(w, "sys", c.ProcessState.SystemTime())
}
