// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build !plan9 && linux

// Copyright 2012-2018 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// rsdp allows to determine the ACPI RSDP structure address which could
// be passed to the boot command later on
// It must be executed at the system init as it relies on scanning
// the kernel messages which could be quickly filled up in some cases
//
// Synopsis:
//
//	rsdp [-f file]
//
// Description:
//
//	Look for rsdp value in a file, default /dev/kmsg
//
// Example:
//
//	rsdp
//	rsdp -f /path/to/file
package bbrsdp

import (
	"flag"
	"fmt"
	"log"

	bbmain "github.com/tunnel-pizza/tunneld/v1alpha1/attach/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/acpi"
)

var cmdUsage string

func usage() {
	log.Fatal(cmdUsage)
}

func registeredMain() {
	flag.Parse()
	if flag.NArg() != 0 {
		usage()
	}
	rsdp, err := acpi.GetRSDP()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf(" acpi_rsdp=%#x \n", rsdp.RSDPAddr())
}
func busyboxInit1() {
	cmdUsage = "Usage: rsdp"
}
func busyboxInit0() {
	busyboxInit1()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("rsdp", registeredInit, registeredMain)
}
