// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

// Copyright 2013-2022 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// readlink display value of symbolic link file.
//
// Synopsis:
//
//	readlink [OPTIONS] [FILE...]
//
// Options:
//
//	-f: follow
//	-n: nonewline
//	-v: verbose
package bbreadlink

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
)

const cmd = "readlink [-fnv] FILE"

var (
	follow    *bool
	noNewLine *bool
	verbose   *bool
)

func busyboxInit4() {
	defUsage := flag.Usage
	flag.Usage = func() {
		os.Args[0] = cmd
		defUsage()
	}
}

func readLink(stdout io.Writer, file string) error {
	path, err := os.Readlink(file)
	if err != nil {
		return err
	}

	if *follow {
		path, err = filepath.EvalSymlinks(file)
	}

	delimiter := "\n"
	if *noNewLine {
		delimiter = ""
	}

	fmt.Fprintf(stdout, "%s%s", path, delimiter)
	return err
}

func run(stdout io.Writer, stderr io.Writer, args []string) error {
	if len(args) == 0 {
		if *verbose {
			fmt.Fprintf(stderr, "missing operand")
		}
		return fmt.Errorf("missing operand")
	}

	var runErr error
	for _, file := range args {
		err := readLink(stdout, file)
		if err != nil {
			if *verbose {
				fmt.Fprintf(stderr, "%v\n", err)
			}
			runErr = err
		}
	}

	return runErr
}

func registeredMain() {
	flag.Parse()
	if err := run(os.Stdout, os.Stderr, flag.Args()); err != nil {
		os.Exit(1)
	}
}
func busyboxInit1() {
	follow = flag.Bool("f", false, "follow recursively")
}
func busyboxInit2() {
	noNewLine = flag.Bool("n", false, "do not output trailing newline")
}
func busyboxInit3() {
	verbose = flag.Bool("v", false, "report error messages")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
}
func registeredInit() {
	busyboxInit0()
	busyboxInit4()
}
func init() {
	bbmain.Register("readlink", registeredInit, registeredMain)
}
