// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build (plan9 || linux) && linux

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// hostname prints or changes the system's hostname.
//
// Synopsis:
//
//	hostname [HOSTNAME]
//
// Author:
//
//	Beletti <rhiguita@gmail.com>
package bbhostname

import (
	"fmt"
	"io"
	"log"
	"os"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
)

func run(stdout io.Writer, args []string) error {
	switch len(args) {
	case 2:
		if err := Sethostname(args[1]); err != nil {
			return fmt.Errorf("could not set hostname: %w", err)
		}
		return nil
	case 1:
		hostname, err := os.Hostname()
		if err != nil {
			return fmt.Errorf("could not obtain hostname: %w", err)
		}
		_, err = fmt.Fprintln(stdout, hostname)
		return err
	default:
		return fmt.Errorf("usage: hostname [HOSTNAME]")
	}
}

func registeredMain() {
	if err := run(os.Stdout, os.Args); err != nil {
		log.Fatal(err)
	}
}
func busyboxInit0() {
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("hostname", registeredInit, registeredMain)
}
