// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build (darwin || dragonfly || freebsd || linux || netbsd || openbsd || solaris) && linux

// Copyright 2012-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package bbinit

import (
	"golang.org/x/sys/unix"
)

func quiesce() error {
	unix.Sync()
	return nil
}
