// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build (!tinygo || tinygo.enable) && linux

// Copyright 2021 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// uefiboot loads the firmware generated by EDK2's UefiPayLoadPkg to boot a UEFI based OS
//
// Synopsis:
//     uefiboot [ARGS] payload
//
// Options:
//     -d: print debug output
//     -i n: Address where to load the payload image
//     -serial_addr  n: serial IO port address
//     -serial_width n: serial port register width
//     -serial_hertz n: serial port input hertz
//     -serial_baud  n: serial port baud rate

package bbuefiboot

import (
	"flag"
	"log"
	"math"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/boot"
	"github.com/u-root/u-root/pkg/boot/uefi"
)

var (
	debug       *bool
	imageBase   *uint64
	serialAddr  *uint
	serialWidth *uint
	serialHertz *uint
	serialBaud  *uint
	execute     *bool
)

var v func(string, ...any)

func registeredMain() {
	flag.Parse()
	if len(flag.Args()) != 1 {
		log.Fatal("Usage: uefiboot <payload>")
	}
	fv, err := uefi.New(flag.Args()[0])
	if err != nil {
		log.Fatal(err)
	}
	if *serialAddr > math.MaxUint32 {
		log.Fatal("Unsupported: serial_addr is greater than uint32.")
	}
	fv.ImageBase, fv.SerialConfig = uintptr(*imageBase), uefi.SerialPortConfig{
		Type:       uefi.SerialPortTypeIO,
		BaseAddr:   uint32(*serialAddr),
		RegWidth:   uint32(*serialWidth),
		InputHertz: uint32(*serialHertz),
		Baud:       uint32(*serialBaud),
	}

	if err := fv.Load(*debug); err != nil {
		log.Fatal(err)
	}

	if *execute {
		if err := boot.Execute(); err != nil {
			log.Fatal(err)
		}
	}
}
func busyboxInit1() {
	debug = flag.Bool("d", false, "Print debug output")
}
func busyboxInit2() {
	imageBase = flag.Uint64("i", 0x800000, "Where to load payload image")
}
func busyboxInit3() {
	serialAddr = flag.Uint("serial_addr", 0x3f8, "Serial IO port address")
}
func busyboxInit4() {
	serialWidth = flag.Uint("serial_width", 1, "Serial port reg width")
}
func busyboxInit5() {
	serialHertz = flag.Uint("serial_hertz", 1843200, "Serial port input hertz")
}
func busyboxInit6() {
	serialBaud = flag.Uint("serial_baud", 115200, "Serial port baud rate")
}
func busyboxInit7() {
	execute = flag.Bool("e", true, "If true, kexec. If not true, just load kernel.")
}
func busyboxInit8() {

	v = func(string, ...any) {}
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
	busyboxInit5()
	busyboxInit6()
	busyboxInit7()
	busyboxInit8()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("uefiboot", registeredInit, registeredMain)
}
