// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

package bbectool

import (
	"flag"
	"fmt"
	"os"
	"time"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
)

type cmd func(...string) error

var (
	// various commands add themselves to this map as part of
	// their init.
	commands    map[string]cmd
	lpcdebug    *bool
	chips       map[string]func(ioport, ioaddr, time.Duration, time.Duration, debugf) ec
	defaultChip *string
	chip        func(p ioport, sa ioaddr, i time.Duration, m time.Duration, d debugf) ec
)

func debug(s string, v ...any) {
	fmt.Printf(s, v...)
}

func registeredMain() {
	d := debug
	flag.Parse()
	if !*lpcdebug {
		d = nil
	}
	p, err := newDevPorts(d)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v", err)
	}
	fmt.Printf("p %v\n", p)
	chip, ok := chips[*defaultChip]
	if !ok {
		fmt.Fprintf(os.Stderr, "Unknown chip %v: Choices: %v\n", *defaultChip, chips)
		os.Exit(1)
	}

	ec := chip(p, ecLpcAddrHostCmd, time.Second*10, time.Second*10, d)
	// valid command?
	// TODO: use the command table for real? But what should the type be? interface{}, err?
	a := flag.Args()
	if len(a) == 0 {
		fmt.Printf("usage: ectool command [args]\n")
		os.Exit(1)
	}
	switch a[0] {
	case "info":
		d, err := info(ec)
		fmt.Printf("%v, %v\n", d, err)
	default:
		fmt.Printf("Unknown: %v", a)
	}
}
func busyboxInit1() {
	lpcdebug = flag.Bool("lpcdebug", true, "Enable lpc debug prints")
}
func busyboxInit2() {
	chips = make(map[string]func(ioport, ioaddr, time.Duration, time.Duration, debugf) ec)
}
func busyboxInit3() {
	defaultChip = flag.String("chip", "lpc", "Which chip to use")
}
func busyboxInit4() {
	chip = newLPC
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
	busyboxInit4()
}
func registeredInit() {
	busyboxInit0()
	busyboxInit5()
}
func init() {
	bbmain.Register("ectool", registeredInit, registeredMain)
}
