// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

package bbectool

import (
	"time"
)

func info(ec ec) ([]byte, error) {
	return ec.Command(ecCmdGetChipInfo, 0, []byte{}, 96 /*len(_ ecResponseGetChipInfo)*/, time.Duration(10*time.Second))
}
