// Code generated by generate.go from github.com/u-root/u-root v0.16.0; DO NOT EDIT.

//go:build (!tinygo || tinygo.enable) && !plan9 && !windows && (darwin || linux)

// Copyright 2016-2017 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// ntpdate uses NTP to adjust the system clock.
//
// Synopsis:
//
//	ntpdate [--config=/etc/ntp.conf] [--rtc] [--verbose] [server ...]
//
// Description:
//
//	ntpdate queries NTP server(s) for time and update system time.
//	If --rtc is specified, it updates the hardware clock as well.
//	Servers to query are obtained from /etc/ntp.conf and/or the command line.
//	By default --config is set to /etc/ntp.conf, config lookup can be disabled
//	by setting --config to an empty string.
//	If servers are specified on the command line, they are tried first.
//	time.google.com is used as the last resort.
//
// Options:
//
//	-w: set hwclock to system clock in UTC
package bbntpdate

import (
	"flag"
	"log"

	bbmain "github.com/tunnel-pizza/tunneld/v0exp1/internal/shell/builtin/internal/bbmain"
	"github.com/u-root/u-root/pkg/ntpdate"
)

var (
	config  *string
	setRTC  *bool
	verbose *bool
)

const (
	fallback = "time.google.com"
)

func registeredMain() {
	flag.Parse()
	if *verbose {
		ntpdate.Debug = log.Printf
	}
	server, offset, err := ntpdate.SetTime(flag.Args(), *config, fallback, *setRTC)
	if err != nil {
		log.Fatalf("Error: %v", err)
	}
	plus := ""
	if offset > 0 {
		plus = "+"
	}
	log.Printf("adjust time server %s offset %s%f sec", server, plus, offset)
}
func busyboxInit1() {
	config = flag.String("config", ntpdate.DefaultNTPConfig, "NTP config file.")
}
func busyboxInit2() {
	setRTC = flag.Bool("rtc", false, "Set RTC time as well")
}
func busyboxInit3() {
	verbose = flag.Bool("verbose", false, "Verbose output")
}
func busyboxInit0() {
	busyboxInit1()
	busyboxInit2()
	busyboxInit3()
}
func registeredInit() {
	busyboxInit0()
}
func init() {
	bbmain.Register("ntpdate", registeredInit, registeredMain)
}
